### ISSUE TITLE
Missing language key

### ISSUE THREAD

**Issue by Galixte** [dmzx/youtubegallery#40]
Hi @vinny @dmzx,

when no category are created there is a text displayed in english: “Uncategorized”. I think it could be translated if there is a language key available.

This text comes from: https://github.com/dmzx/youtubegallery/blob/master/migrations/youtubegallery_install.php#L146.

**Comment by vinny** [comment]
Hi @Galixte 

This is the first category, added when the extension is activated, since is possible edit it in the ACP, I see no reason for this. Anyway, it's a category to be edited or deleted.

One important thing, since the extension was validated/released, is not allowed edit a migration file, this edition is almost impossible.

**Comment by Galixte** [comment]
Thanks for informations.
